Add dark theme and split into vue component and data file
NTUT-rosita/rosita-front pull request #22
Opened 2021-03-02 02:11 UTC by darkfanxing

- Add dark theme at footer
- Split footer component into Vue component and data file (`src/assets/json/footer-data.json`)

2021-03-02 03:29 UTC, Xanonymous-GitHub commented on src/App.vue
> -  <Footer></Footer>
我覺得這樣比較好

2021-03-02 03:35 UTC, Xanonymous-GitHub requested changes
在某情況下會發生字 overflow 狀況：
![](https://i.imgur.com/86a1xQm.webp)

我覺得在 App.vue 的 interfaces 應該要抽出來到獨立的 ts 檔案，甚至把「從json到ts object」的行為抽象出來獨立做，然後在Footer.vue中呼叫並取得data (ex: getFooterData() ... etc.)，這樣其他 components 比較好 import 來用，比如說 Footer.vue 的 props 就可以用 [PropType](https://v3.vuejs.org/guide/typescript-support.html#annotating-props) 寫成 (用我建議的命名的話)
```typescript
props: {
    cardContents: {
      type: Array as PropType<Array<FooterCardContent>>,
      required: true
    },
    legalLinks: {
      type: Array as PropType<Array<FooterLegalLink>>,
      required: true
    },
    communityMediaIcons: {
      type: Array as PropType<Array<CommunityMediaIcon>>,
      required: true
    }
  }
```
然後我覺得 Footer 可以不用 default
再來就是如果要有利於 SEO 的話，footer.vue 的裡面可能需要至少用一次 \<footer\> 標籤來取代 \<div\>

以上只是我的個人建議哦 OwO

2021-03-02 03:43 UTC, Xanonymous-GitHub commented
之後配置好 Vuex 應該可以解決「啊那個獨立的ts檔案要放哪」的問題XD

2021-03-03 07:15 UTC, Xanonymous-GitHub requested changes
in App.vue, Prop names should always use camelCase during declaration, but kebab-case in templates.
see [here](https://v3.vuejs.org/style-guide/#full-word-component-names-strongly-recommended)

2021-03-03 07:18 UTC, Xanonymous-GitHub requested changes

2021-03-03 07:18 UTC, Xanonymous-GitHub commented on src/App.vue
> +  <Footer :cardContents="footerCardContents" :legelLinks="footerLegelLinks" :communityMediaIcons="footerCommunityMediaIcons"></Footer>
There should be fixed:
```vue
<Footer :card-contents="footerCardContents" :legel-links="footerLegelLinks" :community-mediaIcons="footerCommunityMediaIcons"></Footer>
```

2021-03-03 07:19 UTC, Xanonymous-GitHub commented on src/App.vue
> -  <Footer></Footer>
等待 vuex store & services 建制後進行調整。

2021-03-03 13:32 UTC, Xanonymous-GitHub commented
因為更動了Footer 的 import 方式所以產生了 Conflicts 所以到時候我來解XD

2021-03-04 05:33 UTC, Xanonymous-GitHub commented
是kebab-case 不是 camelCase 😶😶😶

2021-03-04 06:12 UTC, darkfanxing reviewed
The commit message should be capital

2021-03-04 06:20 UTC, darkfanxing commented on src/App.vue
> +  <Footer :card-contents="footerCardContents" :community-media-icons="footerCommunityMediaIcons"
prop names 的排版用這樣應該比較好ㄅ

```html
<Footer
  :card-contents="footerCardContents"
  :community-media-icons="footerCommunityMediaIcons"
  :legel-links="footerLegalLinks"
/>

```

2021-03-04 06:27 UTC, Xanonymous-GitHub commented on src/App.vue
> +  <Footer :card-contents="footerCardContents" :community-media-icons="footerCommunityMediaIcons"
我等等修

2021-03-04 08:12 UTC, Xanonymous-GitHub approved these changes
應該好ㄌㄚ

2021-03-04 08:13 UTC, merged